apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: digihot-oppslag
    team: teamdigihot
  name: digihot-oppslag
  namespace: teamdigihot
spec:
  image: {{ image }}
  team: teamdigihot
  liveness:
    path: /internal/is_alive
    initialDelay: 30
    timeout: 100
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    timeout: 100
  ingresses:
    - https://digihot-oppslag.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/metrics
  port: 8080
  replicas:
    max: 1
    min: 1
  accessPolicy:
    inbound:
      rules:
        - application: hm-saksberiker
        - application: hm-soknad-api
        - application: hm-soknadsbehandling
        - application: hm-saksbehandling
        - application: hm-delbestilling-api
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 5m
      memory: 192Mi
  env:
    - name: PORT
      value: "8080"
    - name: KTOR_ENV
      value: production
